host_version: 0.9.0
# download_link: https://github.com/adrianjagielak/universal-desktop-website/releases/download/v0.9.0/UniversalDesktop.MacHost.0.9.0.zip

vision_pro_main_link: https://apps.apple.com/us/app/id6479523407
vision_pro_header_link: https://apps.apple.com/us/app/id6479523407
vision_pro_footer_link: https://apps.apple.com/us/app/id6479523407

#page title
page_title: Universal Desktop # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info  
ios_app_id: 6479523407 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
#ios_app_id: 6477728448 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/UniversalDesktopIcon512.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Universal Desktop # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: $7.99 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Stream Mac apps to your Apple Vision Pro as native visionOS windows.

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Adrian Jagielak
your_link: https://x.com/adrianjagielak
your_city: Gdańsk
email_address: adrianjagielak@gmail.com
facebook_username:
instagram_username:
twitter_username: adrianjagielak
github_username: adrianjagielak
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Stream Mac Apps Natively
    description: Use individual Mac app windows directly on your Apple Vision Pro, like native visionOS apps. No more screen mirroring limitations.
    fontawesome_icon_name: desktop

  - title: Seamless Multi-Device Workflow
    description: Open, close, and resize streamed Mac windows alongside your native visionOS apps. Work fluidly and switch tasks effortlessly.
    fontawesome_icon_name: exchange

  - title: Simple and Secure Setup
    description: Easily connect your Mac and Vision Pro on the same network. Get started in minutes and unlock the power of seamless multi-device work.
    fontawesome_icon_name: link

  - title: "Actively Developed: More to Come!"
    description: "Universal Desktop is constantly evolving. We're actively working on exciting new features like Dock support, Spotlight support, audio support, better support for native input methods, streaming windows from iOS, Windows, and Linux, and many more. Stay tuned for future updates!"
    fontawesome_icon_name: "rocket"

  - title: Let's Chat! # or "Get in Touch"???
    description: I value your feedback! I personally respond to any feedback and suggestions as soon as possible, usually within 24 hours. Don't hesitate to reach out via DM, email, or other channels.
    fontawesome_icon_name: comments

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/udheaderimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
